---
title: "Analysis of Cognition Measure"
author: "Olusoji Oluwafemi Daniel"
date: "18 July 2016"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(markdown)
library(rmarkdown)
library(readr)
library(readxl)
library(dplyr)
library(purrr)
library(stringr)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```

### 

```{r readingdata}
cogdata <- read_excel('./Data/UCHE KELECHUKWU (TEST).xls',sheet = 2,col_names = F)
```

### Filtering out and Cleaning Patient Characteristics

```{r}
patientDetails <- cogdata %>% slice(1:7)
#drop the 2nd and 3rd rows
patientDetails <- patientDetails %>% select(-c(X2,X3)) %>% data.frame()
#cleaning rownames and turning the dataset around
#and later make it variable names
rownames(patientDetails) <- patientDetails[,1]
patientDetails <- patientDetails %>% t() %>% data.frame()
#cleaning new rownames
rownames(patientDetails) <- gsub('X','',rownames(patientDetails))
patientDetails <- patientDetails[-1,]
patientDetails <- as.tbl(patientDetails)
#Cleaning the numeric variables
patientDetails <- patientDetails %>% mutate(Age=as.numeric(Age),duration.of.stroke=as.numeric(duration.of.stroke))
#Cleaning other variables
#getting patients number
patientDetails <- patientDetails %>% mutate(Patient.no=as.numeric(gsub('patient','',Patient.no)))
#the variable name sex was treated as a level of the factor sex
patientDetails <- patientDetails %>% mutate(sex = factor(sex,levels=c('F','M')))
#cleaning the group variable which has the same problme has sex
patientDetails <- patientDetails %>% mutate(group = factor(group,levels=c('A','B')))
#cleaning affected.limb variable which has the same problme has sex
patientDetails <- patientDetails %>% mutate(affected.limb = factor(affected.limb,levels=c('lt','rt')))
#cleaning Handedness variable
patientDetails <- patientDetails %>% mutate(Handedness = tolower(Handedness))
patientDetails <- patientDetails %>% mutate(Handedness=gsub('right','rt',Handedness))
patientDetails <- patientDetails %>% mutate(Handedness = factor(Handedness,levels=c('rt')))
```

### Filtering and Cleaning Measured Variables

```{r}
ms <- cogdata %>% slice(c(1,8:n()))
#renaming spacity appropriately
ms$X1[which(ms$X1=='spasticity')] <- c('wristspasticity','elbowspasticity','shoulderspasticity')
#dealing with the first column
filling <- function(dataset,variable){
  if(!is.character(variable)) stop("variable must be character")
  x <- c(which(!is.na(dataset$variable)),length(dataset$variable))
  a <- numeric(length(dataset$variable))
  a[x] <- dataset$variable[x]
  a[x[length(x)]] <- dataset$variable[x[length(x) - 1]]
  for(i in 2:length(x)){
  if(i < length(x)){ 
      j <- i+1
      a[(x[i]+1):(x[j]-1)] <- dataset$variable[x[i]]
    }
  }
return(a)
}
test <- filling(ms,'X1')
ms$X1 <- a
##subsetting and cleaning the wrist data
wrist <- ms %>% filter(str_detect(X1,'wrist'))
#

```

